/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dlcfbiodata;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Dorcas Adegboye
 */
public class change extends javax.swing.JDialog {
    /**
     * Creates new form change
     */
    
    
    File fi;
     JFileChooser choose;
     Class w;
     String path="C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png";
   
    
    
    public change(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton1");

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BIO DATA REGISTRY", 0, 0, null, new java.awt.Color(255, 51, 0)));
        jPanel3.setForeground(new java.awt.Color(51, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SCHOOL INFO", 0, 0, null, new java.awt.Color(255, 255, 255)));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select district-", "Under God", "Gloryland ", "LH", "Canaanland", "Bethel", "Goodness", "With God ", "Amazing", "Camp Zion", "Olukoko", "LTH", "General", "Best Legacy", "School Of Nursing", "Higher Ground" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel9.setText("District:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select status-", "Member", "Worker", "Exco", "FYB" }));
        jComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorRemoved(evt);
            }
        });

        jLabel13.setText("Status:");

        jLabel14.setText("Unit:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-  select unit  -", "Member", "Prayer", "Choir", "Colporteur", "Ushering", "Evangelism", "Follow-up", "Maintenance", "LTM", "Electrical/Electronic", "G.P.T" }));
        jComboBox3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox3AncestorRemoved(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Dept:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select session-", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", "2025/2026", "2026/2027", "2027/2028", "2028/2029", "2029/2030", "2030/2031" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Session:");

        jLabel17.setText("Level: ");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select level-", "PD", "100L", "200L", "300L", "400L", "500L", "Graduate", "Kopa" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select post-", "Member", "Worker ", "General Coord", "Ass General Coord", "Prayer coord", "Evang Coord", "Follow Coord", "Sis Wel Coord", "Hall Rep", "Kolporteur ", "Libarian", "Choir Master", "Ass. Sis. Wel Coord", "Accad Director", "Secreteriat Coord", "Financial Coord ", "Head Usher", "GPT Head", "Maintenance Coord", "Faculty Head", "Electrical Head", "Electorics Head", "Life Transmission" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jComboBox6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox6AncestorRemoved(evt);
            }
        });

        jLabel18.setText("Post:");

        jLabel19.setText("Campus");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select campus-", "Lautech", "Best Legacy", "School Of Nursing", "Higher Ground" }));
        jComboBox7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox7AncestorRemoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel17)))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox6, 0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFO", 0, 0, null, new java.awt.Color(255, 255, 255)));

        jLabel8.setText("Full Name:");

        jLabel12.setText("Home Address:");

        jLabel4.setText("Hst. Address :");

        jLabel7.setText("Phone No(s).:");

        jLabel11.setText("Select Gender:");

        jLabel10.setText("Email Address:");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Female");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Male ");

        jRadioButton7.setText("jRadioButton7");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(22, 22, 22))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Done");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile image_1.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("UPLOAD PHOTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 153, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/firstImage.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton7)
                            .addComponent(jButton6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEEPER LIFE CAMPUS FELLOWSHIP OGBOMOSO REGION");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dlcfLOGO_1.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("BIODATA APP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
              this.wait();
        } catch (Exception e) {
        }
 
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jTextField1.setText(null);
//        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
         jTextField6.setText(null);
       
        jTextField2.setText(null);
        if (jRadioButton1.isSelected() || jRadioButton2.isSelected()){
            buttonGroup1.clearSelection();
        }
            ImageIcon im = new ImageIcon("C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png");
             //System.out.println("The Image Name : "+im.getImage().toString());
                        
                jLabel1.setIcon(im);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2AncestorRemoved

    private void jComboBox3AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox3AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3AncestorRemoved

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox6AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox6AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6AncestorRemoved

    private void jComboBox7AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox7AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7AncestorRemoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        
         int a=jComboBox1.getSelectedIndex();
        int b=jComboBox2.getSelectedIndex();
        int c=jComboBox3.getSelectedIndex();
        int d=jComboBox4.getSelectedIndex();
        int e=jComboBox5.getSelectedIndex();
        int f=jComboBox6.getSelectedIndex();
        int g=jComboBox7.getSelectedIndex();
                
                String url2="jdbc:mysql://localhost:3306/dlcf_db";
                String rt2="root";
                String pw2="";
                String hg= null;
                String j=null;

if(jTextField4.getText().split(",").length>3){

    JOptionPane.showMessageDialog(this, "CAN'T RECEIVE MORE THAN THREE PHONE NUMBERS ","CAUTION",JOptionPane.INFORMATION_MESSAGE);
}
                else{
    
                     //still working on the mobile number validity    
//                try{
//                
//                String ytr="";
//
//        if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==1) { ytr=jTextField4.getText().trim().replaceAll(" ",null).split(",")[0];}
//        else if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==2){ ytr=jTextField4.getText().trim().replaceAll(" ", null).split(",")[1];}
//        else if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==3) { ytr=jTextField4.getText().trim().replaceAll(" ", "").split(",")[2];}
////                String ytr4=jTextField4.getText().split(",")[3];
////                String ytr5=jTextField4.getText().split(",")[4];
////                
//                
//                Integer.parseInt(ytr);
//               
//                
//                }
//                catch(Exception r){
//                //r.printStackTrace();
//                    //JOptionPane.showMessageDialog(this, "Invalid Phone Number ", "", JOptionPane.ERROR_MESSAGE);
//                    //j="joseph";
//                }
                
                }
             
                
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con2= DriverManager.getConnection(url2, rt2, pw2);
            Statement stm2 = con2.createStatement(ResultSet.CONCUR_READ_ONLY, ResultSet.TYPE_SCROLL_SENSITIVE);
            
            ResultSet req= stm2.executeQuery("Select FirstNAME from All_profile");
            while(req.next()){
                
                String use=jTextField1.getText().trim();
//               
//                 
//                 String white = " ";
//                 
//              int y=  jTextField1.getText().trim().split(" ").length;
//                
//                if (y==2)
//                {
//                 use = jTextField1.getText().trim().split(" ")[0] + " " + jTextField1.getText().trim().split(" ")[1];
//                }
//               else  if (y==3)
//                {
//                use = jTextField1.getText().trim().split(" ")[0] + " " + jTextField1.getText().trim().split(" ")[1] 
//                        +" "+jTextField1.getText().trim().split(" ")[2];
//                }  
//                else  if (y==1 || y==4){
//                
//                    JOptionPane.showMessageDialog(this,"Names Must Be Three(3) or Two(2)","Caution",JOptionPane.ERROR_MESSAGE);
//                }
               
              if (req.getString(1).replaceAll(" ", "").equalsIgnoreCase(use.replaceAll(" ", ""))){
              
              hg= "adegbola stephen";
              
              }
            }
        
        }
        catch(Exception p)
        {
        p.printStackTrace();
        }
        
        
        
        
       if (jTextField1.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the full name ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (hg != null){
       
       JOptionPane.showMessageDialog(this, "Same Name Exist: Possible Duplication Of Names", "Caution", JOptionPane.ERROR_MESSAGE);
       }
       
       //This is the place where Victor edited this code during registration
//      else if (j != null){
//       
//      JOptionPane.showMessageDialog(this, "Invalid Phone Number ", "Caution", JOptionPane.ERROR_MESSAGE);
//       }
       else if(jTextField1.getText().toString().split(" ").length==1 || jTextField1.getText().toString().split(" ").length==4){
       
           JOptionPane.showMessageDialog(this, "You Can Only Input Two/Three Names", "Caution", JOptionPane.ERROR_MESSAGE);
           
       }
       
       else if(a==0){
      JOptionPane.showMessageDialog(this, "Select Session", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
        else if(b==0){
      JOptionPane.showMessageDialog(this, "Select Status", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
         else if(c==0){
      JOptionPane.showMessageDialog(this, "Select Unit", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
          else if(d==0){
      JOptionPane.showMessageDialog(this, "Select District", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
      else if(e==0){
      JOptionPane.showMessageDialog(this, "Select Level", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if(f==0){
      JOptionPane.showMessageDialog(this, "Select Post", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
        else if(g==0){
      JOptionPane.showMessageDialog(this, "Select Campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if((b==1 && c!=1) || (b==1 && f!=1)){
      JOptionPane.showMessageDialog(this, "Member cannot have a unit or post", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==2 && d!=13){
      JOptionPane.showMessageDialog(this, " Select Best Legacy  as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==3 && d!=14){
      JOptionPane.showMessageDialog(this, " Select School of Nursing as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==4 && d!=15){
      JOptionPane.showMessageDialog(this, " Select Higher Ground as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       
       
       else if (jTextField3.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the Hostel Address ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jTextField6.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the  department ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jTextField4.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the Phone Number", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jRadioButton3.isSelected()!=true && jRadioButton4.isSelected()!=true ){
           
       JOptionPane.showMessageDialog(this, "Pls Select Gender ", "Caution", JOptionPane.ERROR_MESSAGE);
      
       }
      else{  
           int l= JOptionPane.showConfirmDialog(this, "Are You Sure You Are Ready To Upload This Profile to the Database","Confrim Input", JOptionPane.YES_NO_OPTION);
           
           if (l==1){return;}
           else {
           
//        String a= jTextField1.getText();
//        String b= jTextField2.getText();
//        String c= jTextField3.getText();
//        String d= jTextField4.getText();
//        String e= jTextField5.getText();
//        int f= jComboBox1.getSelectedIndex();
//        int g= jComboBox2.getSelectedIndex();
//        int h= jComboBox5.getSelectedIndex();
////        int i= jComboBox4.getSelectedIndex();
//        boolean j=  buttonGroup1.isSelected(null);
//       
       // if (a!=null && b!=null && c!=null && d!=null && e!=null && f>0 && g>0 && h>0 && i>0 && j!=false)
        
        FileInputStream fis = null;
        
        //if (jButton2.isSelected())
        {
        try {
            if (path!="C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png"){
           fi= choose.getSelectedFile();
           
          path = fi.getAbsolutePath();
          System.out.print(path);
            fis = new FileInputStream(fi);
            }
        } catch (Exception em) {
            em.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Review Your Input", "Error", JOptionPane.OK_OPTION);
        }
       }
             
            String gender="";
            if (jRadioButton3.isSelected()){
            
                
                gender= "Male";
                
                
            }
            else if (jRadioButton4.isSelected())
            {
                  gender= "Female";
            }
        
            // f = choose.getSelectedFile();
      
                
         //programming 
            
            
            
            try{
                
                String url="jdbc:mysql://localhost:3306/dlcf_db";
                String rt="root";
                String pw="";
                
                // w=Class.forName("com.mysql.jdbc.Driver");
                
                
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection(url, rt, pw);
            Statement stm = con.createStatement(ResultSet.CONCUR_READ_ONLY, ResultSet.TYPE_SCROLL_SENSITIVE);
            PreparedStatement ps= con.prepareStatement("INSERT INTO ALL_PROFILE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            ResultSet re= stm.executeQuery("Select * from All_profile");
            
            String q="Jesus";
            
            while(re.next()){
            
              if (jTextField1.getText().trim().equalsIgnoreCase(re.getString(1))){
                      q= re.getString(1);}
                
            }
            if (q!="Jesus"){
            
                 
                JOptionPane.showMessageDialog(this, "Name Already Exists", "Caution", JOptionPane.INFORMATION_MESSAGE);
                
                
            }
                     else {
            ps.setString(1,jTextField1.getText());
            ps.setString(2, gender);
            ps.setString(3, jComboBox5.getSelectedItem().toString());
            ps.setString(4, jTextField3.getText());
            ps.setString(5, jTextField4.getText());
         
            //ps.setString(6, path);
            ps.setString(6, jComboBox7.getSelectedItem().toString());
          //ps.setString(8,jComboBox6.getSelectedItem().toString());
            ps.setString(7, jComboBox3.getSelectedItem().toString()); 
            ps.setString(8, jTextField2.getText());
            ps.setString(9, jTextField6.getText());
            ps.setString(10, jTextField5.getText());
            ps.setString(11, jComboBox2.getSelectedItem().toString());
            ps.setString(12, jComboBox1.getSelectedItem().toString());
            ps.setString(13, jComboBox6.getSelectedItem().toString());
            ps.setString(14, path.toString());
            ps.setString(15, jComboBox4.getSelectedItem().toString());
//            
//            ps.setString(1, jTextField1.getText());
//          //ps.setString(2, jTextField2.getText());
//            ps.setString(2, jTextField3.getText());
//            ps.setString(2, gender);
//            ps.setString(4, jComboBox2.getSelectedItem().toString());
//            ps.setString(5, jComboBox5.getSelectedItem().toString());
//            ps.setString(6, jTextField4.getText());
//            ps.setString(7, jTextField5.getText());
//            ps.setBinaryStream(8, fis);
//            ps.setString(9,jComboBox1.getSelectedItem().toString());
//            ps.setString(10, jTextField6.getText());
//            ps.setString(11, jTextField2.getText());
//            ps.setString(12,jComboBox7.getSelectedItem().toString());
//            
            int u = ps.executeUpdate();
            
            if (u==1){
             
                JOptionPane.showMessageDialog(this, "Successful Input", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);
                jComboBox4.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
                jComboBox7.setSelectedIndex(0);
                
                ImageIcon im = new ImageIcon("C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png");
                
                jLabel5.setIcon(im);
                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
                jTextField5.setText(null);
                jTextField6.setText(null);
                buttonGroup1.clearSelection();
            }
            else{
                  JOptionPane.showMessageDialog(this, "Revisit your Input", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }
    }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, " Error In Database Input", "Error", JOptionPane.OK_OPTION);
                ex.printStackTrace();
               //JOptionPane.showMessageDialog(this, " Review Your Input","Error Message", JOptionPane.ERROR_MESSAGE);
            //System.out.print("the class name is "+w);
            
            
            
            }
            
       }
           
            
            
       // JOptionPane.showMessageDialog(this, "Done" , "info", JOptionPane.INFORMATION_MESSAGE);
            
        
//        
//        else {
//        
//              JOptionPane.showMessageDialog(this, " Missing Input(s)" , "CAUTION", JOptionPane.INFORMATION_MESSAGE);
//        }
//        
        
        }
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
           choose=new JFileChooser();
        int r= choose.showOpenDialog(this);
        if( r == JFileChooser.APPROVE_OPTION){
            
            fi= choose.getSelectedFile();
            Image img = getToolkit().createImage(fi.getAbsolutePath());
            img = img.getScaledInstance(134,133,Image.SCALE_SMOOTH );
            jLabel5.setIcon(new ImageIcon(img));
            
        }
        //else
        {
        
        
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
         try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception h)
        {
        
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                change dialog = new change(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
