/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dlcfbiodata;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.*;
//import java.io.FileInputStream;
import java.io.IOException;

import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.FileChooserUI;
import javax.xml.bind.annotation.XmlElementDecl.GLOBAL;

/**
 *
 * @author Dorcas Adegboye
 */
public class ProfileBoxInput extends javax.swing.JDialog {
     File fi;
     JFileChooser choose;
     Class w;
     String path="C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png";
   
    // Worker_Input wi;
     
     //choose=new JFileChooser();
     
    /**
     * Creates new form ProfileBoxInput
     */
     
     //choose=new JFileChooser();
     
    public ProfileBoxInput(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
       }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile Input");
        setBounds(new java.awt.Rectangle(450, 25, 0, 0));
        setIconImage(null);
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setForeground(new java.awt.Color(0, 51, 204));
        jButton2.setText("Upload Photo");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile image_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );

        jLabel4.setText("Hst. Address :");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select session-", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", "2025/2026", "2026/2027", "2027/2028", "2028/2029", "2029/2030", "2030/2031" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Session:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select level-", "PD", "100L", "200L", "300L", "400L", "500L", "Graduate", "Kopa" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Level: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("select gender "));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select status-", "Member", "Worker", "Exco", "FYB" }));
        jComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorRemoved(evt);
            }
        });

        jLabel7.setText("Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Dept:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jLabel10.setText("Email Address:");

        jLabel5.setText("Phone No(s).:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Done ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Unit:");

        jLabel14.setText("Post:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-  select unit  -", "Member", "Prayer", "Choir", "Colporteur", "Ushering", "Evangelism", "Follow-up", "Maintenance", "LTM", "Electrical/Electronic", "G.P.T" }));
        jComboBox3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox3AncestorRemoved(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select post-", "Member", "Worker ", "General Coord", "Ass General Coord", "Prayer coord", "Evang Coord", "Follow Coord", "Sis Wel Coord", "Hall Rep", "Kolporteur ", "Libarian", "Choir Master", "Ass. Sis. Wel Coord", "Accad Director", "Secreteriat Coord", "Financial Coord ", "Head Usher", "GPT Head", "Maintenance Coord", "Faculty Head", "Electrical Head", "Electorics Head", "Life Transmission" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jComboBox6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox6AncestorRemoved(evt);
            }
        });

        jLabel8.setText("Full Name:");

        jLabel12.setText("Home Address:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select campus-", "Lautech", "Best Legacy", "School Of Nursing", "Higher Ground" }));
        jComboBox7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox7AncestorRemoved(evt);
            }
        });

        jLabel15.setText("Campus");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select district-", "Under God", "Gloryland ", "LH", "Canaanland", "Bethel", "Goodness", "With God ", "Amazing", "Camp Zion", "Olukoko", "LTH", "General", "Best Legacy", "School Of Nursing", "Higher Ground" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel2.setText("District:");

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox7, 0, 1, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorRemoved
        // TODO add your handling code here:  
    }//GEN-LAST:event_jComboBox2AncestorRemoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int a=jComboBox1.getSelectedIndex();
        int b=jComboBox2.getSelectedIndex();
        int c=jComboBox3.getSelectedIndex();
        int d=jComboBox4.getSelectedIndex();
        int e=jComboBox5.getSelectedIndex();
        int f=jComboBox6.getSelectedIndex();
        int g=jComboBox7.getSelectedIndex();
                
                String url2="jdbc:mysql://localhost:3306/dlcf_db";
                String rt2="root";
                String pw2="";
                String hg= null;
                String j=null;

if(jTextField4.getText().split(",").length>3){

    JOptionPane.showMessageDialog(this, "CAN'T RECEIVE MORE THAN THREE PHONE NUMBERS ","CAUTION",JOptionPane.INFORMATION_MESSAGE);
}
                else{
    
                     //still working on the mobile number validity    
//                try{
//                
//                String ytr="";
//
//        if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==1) { ytr=jTextField4.getText().trim().replaceAll(" ",null).split(",")[0];}
//        else if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==2){ ytr=jTextField4.getText().trim().replaceAll(" ", null).split(",")[1];}
//        else if (jTextField4.getText().trim().replaceAll(" ", null).split(",").length==3) { ytr=jTextField4.getText().trim().replaceAll(" ", "").split(",")[2];}
////                String ytr4=jTextField4.getText().split(",")[3];
////                String ytr5=jTextField4.getText().split(",")[4];
////                
//                
//                Integer.parseInt(ytr);
//               
//                
//                }
//                catch(Exception r){
//                //r.printStackTrace();
//                    //JOptionPane.showMessageDialog(this, "Invalid Phone Number ", "", JOptionPane.ERROR_MESSAGE);
//                    //j="joseph";
//                }
                
                }
             
                
        try{
        Class.forName("com.mysql.jdbc.Driver");
            Connection con2= DriverManager.getConnection(url2, rt2, pw2);
            Statement stm2 = con2.createStatement(ResultSet.CONCUR_READ_ONLY, ResultSet.TYPE_SCROLL_SENSITIVE);
            
            ResultSet req= stm2.executeQuery("Select FirstNAME from All_profile");
            while(req.next()){
                
                String use=jTextField1.getText().trim();
//               
//                 
//                 String white = " ";
//                 
//              int y=  jTextField1.getText().trim().split(" ").length;
//                
//                if (y==2)
//                {
//                 use = jTextField1.getText().trim().split(" ")[0] + " " + jTextField1.getText().trim().split(" ")[1];
//                }
//               else  if (y==3)
//                {
//                use = jTextField1.getText().trim().split(" ")[0] + " " + jTextField1.getText().trim().split(" ")[1] 
//                        +" "+jTextField1.getText().trim().split(" ")[2];
//                }  
//                else  if (y==1 || y==4){
//                
//                    JOptionPane.showMessageDialog(this,"Names Must Be Three(3) or Two(2)","Caution",JOptionPane.ERROR_MESSAGE);
//                }
               
              if (req.getString(1).replaceAll(" ", "").equalsIgnoreCase(use.replaceAll(" ", ""))){
              
              hg= "adegbola stephen";
              
              }
            }
        
        }
        catch(Exception p)
        {
        p.printStackTrace();
        }
        
        
        
        
       if (jTextField1.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the full name ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (hg != null){
       
       JOptionPane.showMessageDialog(this, "Same Name Exist: Possible Duplication Of Names", "Caution", JOptionPane.ERROR_MESSAGE);
       }
       
       //This is the place where Victor edited this code during registration
//      else if (j != null){
//       
//      JOptionPane.showMessageDialog(this, "Invalid Phone Number ", "Caution", JOptionPane.ERROR_MESSAGE);
//       }
       else if(jTextField1.getText().toString().split(" ").length==1 || jTextField1.getText().toString().split(" ").length==4){
       
           JOptionPane.showMessageDialog(this, "You Can Only Input Two/Three Names", "Caution", JOptionPane.ERROR_MESSAGE);
           
       }
       
       else if(a==0){
      JOptionPane.showMessageDialog(this, "Select Session", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
        else if(b==0){
      JOptionPane.showMessageDialog(this, "Select Status", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
         else if(c==0){
      JOptionPane.showMessageDialog(this, "Select Unit", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
          else if(d==0){
      JOptionPane.showMessageDialog(this, "Select District", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
      else if(e==0){
      JOptionPane.showMessageDialog(this, "Select Level", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if(f==0){
      JOptionPane.showMessageDialog(this, "Select Post", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
        else if(g==0){
      JOptionPane.showMessageDialog(this, "Select Campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if((b==1 && c!=1) || (b==1 && f!=1)){
      JOptionPane.showMessageDialog(this, "Member cannot have a unit or post", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==2 && d!=13){
      JOptionPane.showMessageDialog(this, " Select Best Legacy  as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==3 && d!=14){
      JOptionPane.showMessageDialog(this, " Select School of Nursing as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if( g==4 && d!=15){
      JOptionPane.showMessageDialog(this, " Select Higher Ground as district or campus", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       
       
       else if (jTextField3.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the Hostel Address ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jTextField6.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the  department ", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jTextField4.getText().toString().isEmpty()){
           
       JOptionPane.showMessageDialog(this, "Enter in the Phone Number", "Caution", JOptionPane.ERROR_MESSAGE);
       
       }
       else if (jRadioButton1.isSelected()!=true && jRadioButton2.isSelected()!=true ){
           
       JOptionPane.showMessageDialog(this, "Pls Select Gender ", "Caution", JOptionPane.ERROR_MESSAGE);
      
       }
      else{  
           int l= JOptionPane.showConfirmDialog(this, "Are You Sure You Are Ready To Upload This Profile to the Database","Confrim Input", JOptionPane.YES_NO_OPTION);
           
           if (l==1){return;}
           else {
           
//        String a= jTextField1.getText();
//        String b= jTextField2.getText();
//        String c= jTextField3.getText();
//        String d= jTextField4.getText();
//        String e= jTextField5.getText();
//        int f= jComboBox1.getSelectedIndex();
//        int g= jComboBox2.getSelectedIndex();
//        int h= jComboBox5.getSelectedIndex();
////        int i= jComboBox4.getSelectedIndex();
//        boolean j=  buttonGroup1.isSelected(null);
//       
       // if (a!=null && b!=null && c!=null && d!=null && e!=null && f>0 && g>0 && h>0 && i>0 && j!=false)
        
        FileInputStream fis = null;
        
        //if (jButton2.isSelected())
        {
        try {
            if (path!="C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png"){
           fi= choose.getSelectedFile();
           
          path = fi.getAbsolutePath();
          System.out.print(path);
            fis = new FileInputStream(fi);
            }
        } catch (Exception em) {
            em.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Review Your Input", "Error", JOptionPane.OK_OPTION);
        }
       }
             
            String gender="";
            if (jRadioButton1.isSelected()){
            
                
                gender= "Male";
                
                
            }
            else if (jRadioButton2.isSelected())
            {
                  gender= "Female";
            }
        
            // f = choose.getSelectedFile();
      
                
         //programming 
            
            
            
            try{
                
                String url="jdbc:mysql://localhost:3306/dlcf_db";
                String rt="root";
                String pw="";
                
                // w=Class.forName("com.mysql.jdbc.Driver");
                
                
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= DriverManager.getConnection(url, rt, pw);
            Statement stm = con.createStatement(ResultSet.CONCUR_READ_ONLY, ResultSet.TYPE_SCROLL_SENSITIVE);
            PreparedStatement ps= con.prepareStatement("INSERT INTO ALL_PROFILE VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            ResultSet re= stm.executeQuery("Select * from All_profile");
            
            String q="Jesus";
            
            while(re.next()){
            
              if (jTextField1.getText().trim().equalsIgnoreCase(re.getString(1))){
                      q= re.getString(1);}
                
            }
            if (q!="Jesus"){
            
                 
                JOptionPane.showMessageDialog(this, "Name Already Exists", "Caution", JOptionPane.INFORMATION_MESSAGE);
                
                
            }
                     else {
            ps.setString(1,jTextField1.getText());
            ps.setString(2, gender);
            ps.setString(3, jComboBox5.getSelectedItem().toString());
            ps.setString(4, jTextField3.getText());
            ps.setString(5, jTextField4.getText());
         
            //ps.setString(6, path);
            ps.setString(6, jComboBox7.getSelectedItem().toString());
          //ps.setString(8,jComboBox6.getSelectedItem().toString());
            ps.setString(7, jComboBox3.getSelectedItem().toString()); 
            ps.setString(8, jTextField2.getText());
            ps.setString(9, jTextField6.getText());
            ps.setString(10, jTextField5.getText());
            ps.setString(11, jComboBox2.getSelectedItem().toString());
            ps.setString(12, jComboBox1.getSelectedItem().toString());
            ps.setString(13, jComboBox6.getSelectedItem().toString());
            ps.setString(14, path.toString());
            ps.setString(15, jComboBox4.getSelectedItem().toString());
//            
//            ps.setString(1, jTextField1.getText());
//          //ps.setString(2, jTextField2.getText());
//            ps.setString(2, jTextField3.getText());
//            ps.setString(2, gender);
//            ps.setString(4, jComboBox2.getSelectedItem().toString());
//            ps.setString(5, jComboBox5.getSelectedItem().toString());
//            ps.setString(6, jTextField4.getText());
//            ps.setString(7, jTextField5.getText());
//            ps.setBinaryStream(8, fis);
//            ps.setString(9,jComboBox1.getSelectedItem().toString());
//            ps.setString(10, jTextField6.getText());
//            ps.setString(11, jTextField2.getText());
//            ps.setString(12,jComboBox7.getSelectedItem().toString());
//            
            int u = ps.executeUpdate();
            
            if (u==1){
             
                JOptionPane.showMessageDialog(this, "Successful Input", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);
                jComboBox4.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
                jComboBox7.setSelectedIndex(0);
                
                ImageIcon im = new ImageIcon("C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png");
                
                jLabel1.setIcon(im);
                jTextField1.setText(null);
                jTextField2.setText(null);
                jTextField3.setText(null);
                jTextField4.setText(null);
                jTextField5.setText(null);
                jTextField6.setText(null);
                buttonGroup1.clearSelection();
            }
            else{
                  JOptionPane.showMessageDialog(this, "Revisit your Input", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }
    }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, " Error In Database Input", "Error", JOptionPane.OK_OPTION);
                ex.printStackTrace();
               //JOptionPane.showMessageDialog(this, " Review Your Input","Error Message", JOptionPane.ERROR_MESSAGE);
            //System.out.print("the class name is "+w);
            
            
            
            }
            
       }
           
            
            
       // JOptionPane.showMessageDialog(this, "Done" , "info", JOptionPane.INFORMATION_MESSAGE);
            
        
//        
//        else {
//        
//              JOptionPane.showMessageDialog(this, " Missing Input(s)" , "CAUTION", JOptionPane.INFORMATION_MESSAGE);
//        }
//        
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        choose=new JFileChooser();
        int r= choose.showOpenDialog(this);
        if( r == JFileChooser.APPROVE_OPTION){
            
            fi= choose.getSelectedFile();
            Image img = getToolkit().createImage(fi.getAbsolutePath());
            img = img.getScaledInstance(134,133,Image.SCALE_SMOOTH );
            jLabel1.setIcon(new ImageIcon(img));
            
        }
        //else
        {
        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
              this.wait();
        } catch (Exception e) {
        }
 
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jTextField1.setText(null);
//        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
         jTextField6.setText(null);
       
        jTextField2.setText(null);
        if (jRadioButton1.isSelected() || jRadioButton2.isSelected()){
            buttonGroup1.clearSelection();
        }
            ImageIcon im = new ImageIcon("C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\profile image_1.png");
             //System.out.println("The Image Name : "+im.getImage().toString());
                        
                jLabel1.setIcon(im);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox3AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3AncestorRemoved

    private void jComboBox6AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox6AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6AncestorRemoved

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox7AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox7AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7AncestorRemoved

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         ImageIcon img = new ImageIcon("C:\\Users\\Dorcas Adegboye\\Documents\\NetBeansProjects\\DlcfBiodata\\src\\Images\\dlcfLOGO.jpg");
            this.setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowOpened

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
     
      //  jButton2.setForeground(Color.white);
         //jButton2.setBackground(Color.blue);
        //jButton2.setForeground(Color.blue);
        
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
       // jButton2.setBackground(Color.white);
    }//GEN-LAST:event_jButton2MouseReleased

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileBoxInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileBoxInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileBoxInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileBoxInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfileBoxInput dialog = new ProfileBoxInput(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
